name: discord_bot
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  logger: ^2.0.2+1
  nyxx: ^6.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
